name: Generate ASCII artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, Iam a DRAGON ... RAWR" > dragon.txt
        
        - name: Read File
          run: cat dragon.txt
        
        # - name: List Files
        #   run: ls
        
        # - name: Read File
        #   run: cat README.md